Jenny.SearchPaths = Assets/Libraries/Entitas/Entitas.CodeGeneration.Plugins
Jenny.Plugins = Entitas.CodeGeneration.Plugins
Jenny.DataProviders = Entitas.CodeGeneration.Plugins
Jenny.CodeGenerators = Entitas.CodeGeneration.Plugins
Jenny.PostProcessors = Entitas.CodeGeneration.Plugins
Entitas.VisualDebugging.Unity.Editor.SystemWarningThreshold = 5
Entitas.VisualDebugging.Unity.Editor.DefaultInstanceCreatorFolderPath = Assets/Editor/DefaultInstanceCreator
Entitas.VisualDebugging.Unity.Editor.TypeDrawerFolderPath = Assets/Editor/TypeDrawer
